%YAML:1.0
---
serial_device: /dev/rfcomm0
ir_width: 510
ir_height: 260
output_width: 194
output_height: 221
output_x_min: 26
output_y_min: 70
min_blob_size: 1.75
max_blob_size: 250.0
ir_threshold: 100.0
use_perspective_intersection: 0
i2c_device: /dev/i2c-1
use_dfrobot:0
frame_width:640
frame_height:480
