%YAML:1.0
---
serial_device: /dev/rfcomm0
ir_width: 510
ir_height: 260
output_width: 180
output_height: 220
output_x_min: 1
output_y_min: 40
min_blob_size: 1.75
max_blob_size: 250.0
ir_threshold: 100.0
